[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2018"
name = "aux11"
version = "0.1.0"

[dependencies]
cortex-m = "0.6.3"
cortex-m-rt = "0.6.12"
panic-itm = "0.4.1"

[dependencies.f3]
features = ["rt"]
version = "0.6.1"

[features]
adapter = []

